FROM node:18-alpine3.15 as build

WORKDIR /app
COPY . /app

ARG VITE_STRIPE_PK
ARG VITE_APP_URL
ARG VITE_WS_URL

RUN yarn
RUN yarn run build

FROM nginx as main
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80