# Generated by Django 4.2.7 on 2023-11-22 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('author', models.TextField(blank=True)),
                ('amount', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
