version: "3.7"

services:
  webserver:
    image: ghcr.io/jensjeflensje/premium.onlyjens.nl-frontend:production
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8081:80"
    depends_on:
      - backend
  database:
    image: postgres:15.4-alpine
    environment:
      POSTGRES_DB: onlyjens
      POSTGRES_PASSWORD: onlyjens
    volumes:
      - postgres-data:/var/lib/postgresql/data
  backend:
    command: daphne -b=0.0.0.0 -p 8000 onlyjens.asgi:application
    image: ghcr.io/jensjeflensje/premium.onlyjens.nl-backend:production
    env_file:
      - .env
    depends_on:
      - database
      - redis
  backend_worker:
    command: python3 manage.py qcluster
    image: ghcr.io/jensjeflensje/premium.onlyjens.nl-backend:production
    env_file:
      - .env
    depends_on:
      - database
      - redis
  redis:
    image: redis:7.4.4-alpine

volumes:
  postgres-data:
