version: "3.7"

services:
  webserver:
    image: nginx
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:8081"
    depends_on:
      - backend
  database:
    image: postgres:15.4-alpine
    environment:
      POSTGRES_DB: onlyjens
      POSTGRES_PASSWORD: onlyjens
    volumes:
      - postgres-data:/var/lib/postgresql/data
  backend:
    command: gunicorn --bind=0.0.0.0:8000 onlyjens.wsgi:application
    image: ghcr.io/jensjeflensje/premium.onlyjens.nl-backend:production
    env_file:
      - .env
    depends_on:
      - database
      - redis
  backend_worker:
    command: python3 manage.py qcluster
    image: ghcr.io/jensjeflensje/premium.onlyjens.nl-backend:production
    env_file:
      - .env
    depends_on:
      - database
      - redis
  redis:
    image: redis:latest

volumes:
  postgres-data:
